name: velvet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  formz: ^0.7.0
  event_bus: ^2.0.0
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  path_provider: ^2.1.3
  http: ^1.2.1
  dropdown_textfield: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/velvet_png.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/velvet_icono.png"
